services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    environment:
      APP_ENV: production
      APP_DEBUG: "false"
      APP_URL: ${APP_URL}
      ASSET_URL: ${ASSET_URL}
      APP_KEY: ${APP_KEY}
      # DB
      DB_CONNECTION: pgsql
      DB_HOST: db
      DB_PORT: ${DB_PORT}
      DB_DATABASE: ${DB_DATABASE}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}

      # REDIS
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
      REDIS_PASSWORD: ${REDIS_PASSWORD}

      MAIL_MAILER: ${MAIL_MAILER}
      MAIL_HOST: ${MAIL_HOST}
      MAIL_PORT: ${MAIL_PORT}
      MAIL_USERNAME: ${MAIL_USERNAME}
      MAIL_PASSWORD: ${MAIL_PASSWORD}
      MAIL_ENCRYPTION: ${MAIL_ENCRYPTION}
      MAIL_FROM_ADDRESS: ${MAIL_FROM_ADDRESS}
      MAIL_FROM_NAME: ${MAIL_FROM_NAME}


      CAS_HOSTNAME: ${CAS_HOSTNAME}
      CAS_REAL_HOSTS: ${CAS_REAL_HOSTS}
      CAS_CLIENT_SERVICE: ${CAS_CLIENT_SERVICE}
      CAS_LOGOUT_URL: ${CAS_LOGOUT_URL}
      CAS_LOG: ${CAS_LOG}
      CAS_MASQUERADE: ${CAS_MASQUERADE}

      RUN_MIGRATIONS: "true"
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    ports:
      - "9001:9001"


  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USERNAME} -d ${DB_DATABASE}"]
      timeout: 20s
      retries: 10
      start_period: 40s
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
  redis_data:
